// @title DJJS Event Reporting API
// @version 1.0
// @description API documentation for the DJJS Event Reporting Backend.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.email vaish@gmail.com

// @license.name MIT
// @license.url https://opensource.org/licenses/MIT

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

// @host localhost:8080
// @BasePath /
package main

import (
	"log"
	"os"
	"time"

	"github.com/followCode/djjs-event-reporting-backend/app/handlers"
	"github.com/followCode/djjs-event-reporting-backend/app/middleware"
	"github.com/followCode/djjs-event-reporting-backend/config"
	"github.com/gin-contrib/cors"
	"github.com/joho/godotenv"

	"github.com/gin-gonic/gin"

	swaggerFiles "github.com/swaggo/files"     // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware

	_ "github.com/followCode/djjs-event-reporting-backend/docs" // docs is generated by Swag CLI
)

func main() {

	if err := godotenv.Load(); err != nil {
		log.Println("Warning: .env file not found, using system env variables")
	}
	// 1️⃣ Connect to Postgres
	config.ConnectDB()

	// 2️⃣ Set JWT secret from environment
	jwtSecret := os.Getenv("JWT_SECRET")
	if jwtSecret == "" {
		log.Fatal("JWT_SECRET is missing in .env")
	}
	config.JWTSecret = []byte(jwtSecret)

	// 3️⃣ Create Gin router
	r := gin.Default()

	// Enable CORS for Angular frontend
	r.Use(cors.New(cors.Config{
		AllowOrigins:     []string{"*"},
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"*"},
		ExposeHeaders:    []string{"Content-Length", "Authorization"},
		AllowCredentials: false, // must be false if AllowOrigins = "*"
		MaxAge:           12 * time.Hour,
	}))

	// Swagger documentation route
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// 5️⃣ Public routes
	r.POST("/login", handlers.LoginHandler)

	// Protected routes
	r.POST("/logout", middleware.AuthMiddleware(), handlers.LogoutHandler)

	// 6️⃣ Protected route example
	r.GET("/protected", middleware.AuthMiddleware(), func(c *gin.Context) {
		userID, _ := c.Get("userID")
		roleID, _ := c.Get("roleID")
		c.JSON(200, gin.H{
			"message": "You are authorized",
			"userID":  userID,
			"roleID":  roleID,
		})
	})

	// CRUD APIs
	api := r.Group("/api")
	{
		// AREA CRUD
		api.POST("/areas", middleware.AuthMiddleware(), handlers.CreateAreaHandler)
		api.GET("/areas", middleware.AuthMiddleware(), handlers.GetAllAreasHandler)
		api.GET("/areas/:id", middleware.AuthMiddleware(), handlers.GetAreaSearchHandler)
		api.PUT("/areas/:id", middleware.AuthMiddleware(), handlers.UpdateAreaHandler)
		api.DELETE("/areas/:id", middleware.AuthMiddleware(), handlers.DeleteAreaHandler)

		// Users CRUD
		api.POST("/users", middleware.AuthMiddleware(), handlers.CreateUserHandler)
		api.GET("/users", middleware.AuthMiddleware(), handlers.GetAllUsersHandler)
		api.GET("/users/:id", middleware.AuthMiddleware(), handlers.GetUserSearchHandler)
		api.PUT("/users/:id", middleware.AuthMiddleware(), handlers.UpdateUserHandler)
		api.DELETE("/users/:id", middleware.AuthMiddleware(), handlers.DeleteUserHandler)

		// Promotion CRUD
		api.POST("/promotion-material-details", middleware.AuthMiddleware(), handlers.CreatePromotionMaterialDetailsHandler)
		api.GET("/promotion-material-details", middleware.AuthMiddleware(), handlers.GetAllPromotionMaterialDetailsHandler)
		api.GET("/promotion-material-details/event/:event_id", middleware.AuthMiddleware(), handlers.GetPromotionMaterialDetailsByEventIDHandler)
		api.PUT("/promotion-material-details/:id", middleware.AuthMiddleware(), handlers.UpdatePromotionMaterialDetailsHandler)
		api.DELETE("/promotion-material-details/:id", middleware.AuthMiddleware(), handlers.DeletePromotionMaterialDetailsHandler)

		// Media CRUD
		api.POST("/event-media", middleware.AuthMiddleware(), handlers.CreateEventMediaHandler)
		api.GET("/event-media", middleware.AuthMiddleware(), handlers.GetAllEventMediaHandler)
		api.GET("/event-media/event/:event_id", middleware.AuthMiddleware(), handlers.GetEventMediaByEventIDHandler)
		api.PUT("/event-media/:id", middleware.AuthMiddleware(), handlers.UpdateEventMediaHandler)
		api.DELETE("/event-media/:id", middleware.AuthMiddleware(), handlers.DeleteEventMediaHandler)

		// Branch CRUD
		api.POST("/branches", middleware.AuthMiddleware(), handlers.CreateBranchHandler)
		api.GET("/branches", middleware.AuthMiddleware(), handlers.GetAllBranchesHandler)
		api.GET("/branches/search", middleware.AuthMiddleware(), handlers.GetBranchSearchHandler)
		api.PUT("/branches/:id", middleware.AuthMiddleware(), handlers.UpdateBranchHandler)
		api.DELETE("/branches/:id", middleware.AuthMiddleware(), handlers.DeleteBranchHandler)

		//branch-infra CRUD
		api.POST("/branch-infra", middleware.AuthMiddleware(), handlers.CreateBranchInfrastructureHandler)
		api.GET("/branch-infra", middleware.AuthMiddleware(), handlers.GetAllBranchInfrastructureHandler)
		api.GET("/branch-infra/branch/:branch_id", middleware.AuthMiddleware(), handlers.GetInfrastructureByBranchHandler)
		api.PUT("/branch-infra/:id", middleware.AuthMiddleware(), handlers.UpdateBranchInfrastructureHandler)
		api.DELETE("/branch-infra/:id", middleware.AuthMiddleware(), handlers.DeleteBranchInfrastructureHandler)

		//branch-member CRUD
		api.POST("/branch-member", middleware.AuthMiddleware(), handlers.CreateBranchMemberHandler)
		api.GET("/branch-member", middleware.AuthMiddleware(), handlers.GetAllBranchMembersHandler)
		api.GET("/branch-member/branch/:branch_id", middleware.AuthMiddleware(), handlers.GetMembersByBranchHandler)
		api.PUT("/branch-member/:id", middleware.AuthMiddleware(), handlers.UpdateBranchMemberHandler)
		api.DELETE("/branch-member/:id", middleware.AuthMiddleware(), handlers.DeleteBranchMemberHandler)

		// SpecialGuests CRUD
		api.POST("/specialguests", middleware.AuthMiddleware(), handlers.CreateSpecialGuestHandler)
		api.GET("/specialguests", middleware.AuthMiddleware(), handlers.GetAllSpecialGuestsHandler)
		api.GET("/events/:event_id/specialguests", middleware.AuthMiddleware(), handlers.GetSpecialGuestByEventID)
		api.PUT("/specialguests/:id", middleware.AuthMiddleware(), middleware.ValidateSpecialGuestMiddleware(), handlers.UpdateSpecialGuestHandler)
		api.DELETE("/specialguests/:id", middleware.AuthMiddleware(), middleware.ValidateSpecialGuestMiddleware(), handlers.DeleteSpecialGuestHandler)

		// Volunteers CRUD
		api.POST("/volunteers", middleware.AuthMiddleware(), handlers.CreateVolunteerHandler)
		api.GET("/volunteers", middleware.AuthMiddleware(), handlers.GetAllVolunteersHandler)
		api.GET("/events/:event_id/volunteers", middleware.AuthMiddleware(), handlers.GetVolunteerByEventID)
		api.PUT("/volunteers/:id", middleware.AuthMiddleware(), middleware.ValidateVolunteerMiddleware(), handlers.UpdateVolunteerHandler)
		api.DELETE("/volunteers/:id", middleware.AuthMiddleware(), middleware.ValidateVolunteerMiddleware(), handlers.DeleteVolunteerHandler)

		// Event CRUD Routes
		api.POST("/events", middleware.AuthMiddleware(), handlers.CreateEventHandler)
		api.GET("/events", middleware.AuthMiddleware(), handlers.GetAllEventsHandler)
		api.GET("/events/search", middleware.AuthMiddleware(), handlers.SearchEventsHandler)
		api.PUT("/events/:id", middleware.AuthMiddleware(), handlers.UpdateEventHandler)
		api.DELETE("/events/:id", middleware.AuthMiddleware(), handlers.DeleteEventHandler)

	}

	// 7️⃣ Start server
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("Server starting on port %s...", port)
	if err := r.Run(":" + port); err != nil {
		log.Fatalf("Failed to run server: %v", err)
	}
}
