// @title DJJS Event Reporting API
// @version 1.0
// @description API documentation for the DJJS Event Reporting Backend.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.email vaish@gmail.com

// @license.name MIT
// @license.url https://opensource.org/licenses/MIT

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

// @host localhost:8080
// @BasePath /
package main

import (
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/followCode/djjs-event-reporting-backend/app/api"
	"github.com/followCode/djjs-event-reporting-backend/app/middleware"
	"github.com/followCode/djjs-event-reporting-backend/app/services"
	"github.com/followCode/djjs-event-reporting-backend/config"
	"github.com/gin-contrib/cors"
	"github.com/joho/godotenv"

	"github.com/gin-gonic/gin"

	swaggerFiles "github.com/swaggo/files"     // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware

	_ "github.com/followCode/djjs-event-reporting-backend/docs" // docs is generated by Swag CLI
)

func main() {
	// Load environment variables from .env file
	// Try multiple locations to find .env file
	wd, _ := os.Getwd()
	envPaths := []string{
		".env",                              // Current directory
		filepath.Join(wd, ".env"),          // Absolute path from working directory
		filepath.Join("..", "..", ".env"),  // Two levels up (if running from app/main/)
	}
	
	var loaded bool
	for _, envPath := range envPaths {
		if err := godotenv.Load(envPath); err == nil {
			log.Printf("Loaded .env file from: %s", envPath)
			loaded = true
			break
		} else {
			// Debug: log the error for troubleshooting
			log.Printf("Failed to load .env from %s: %v", envPath, err)
		}
	}
	
	if !loaded {
		log.Printf("Warning: .env file not found in any of these locations: %v", envPaths)
		log.Printf("Current working directory: %s", wd)
		log.Println("Continuing with system environment variables...")
	}

	// 1️⃣ Connect to Postgres (legacy GORM connection for existing routes)
	config.ConnectDB()

	// 1️⃣b Initialize new auth system config (pgx + Redis)
	if err := config.LoadAuthConfig(); err != nil {
		log.Fatalf("Failed to load auth config: %v", err)
	}

	// 2️⃣ Set JWT secret from environment (legacy - also set in internal config)
	jwtSecret := os.Getenv("JWT_SECRET")
	if jwtSecret == "" {
		log.Fatal("JWT_SECRET is missing in .env")
	}
	config.JWTSecret = []byte(jwtSecret)

	// 3️⃣ Initialize S3
	if err := services.InitializeS3(); err != nil {
		log.Printf("Warning: Failed to initialize S3: %v", err)
	}

	// 4️⃣ Create Gin router
	r := gin.New()
	
	// Add recovery middleware (gin.Default includes this, but we want to control it)
	r.Use(gin.Recovery())
	
	// Add logger middleware only in debug mode
	if gin.Mode() == gin.DebugMode {
		r.Use(gin.Logger())
	}

	// Add timeout middleware (30 seconds)
	r.Use(middleware.TimeoutMiddleware(30 * time.Second))

	// Enable CORS for Angular frontend
	// Get allowed origins from environment - REQUIRED in production
	allowedOrigins := os.Getenv("ALLOWED_ORIGINS")
	if allowedOrigins == "" {
		if gin.Mode() == gin.DebugMode {
			// Only allow localhost in debug mode
			allowedOrigins = "http://localhost:4200,http://localhost:3000"
			log.Println("Warning: ALLOWED_ORIGINS not set, using localhost defaults (debug mode only)")
		} else {
			log.Fatal("ALLOWED_ORIGINS environment variable is required in production")
		}
	}
	
	origins := []string{}
	for _, origin := range strings.Split(allowedOrigins, ",") {
		origins = append(origins, strings.TrimSpace(origin))
	}
	
	r.Use(cors.New(cors.Config{
		AllowOrigins:     origins,
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Content-Length", "Accept-Encoding", "X-CSRF-Token", "Authorization", "accept", "origin", "Cache-Control", "X-Requested-With"},
		ExposeHeaders:    []string{"Content-Length", "Authorization"},
		AllowCredentials: true,
		MaxAge:           12 * time.Hour,
	}))

	// Swagger documentation route - only enable if ENABLE_SWAGGER is set to "true"
	// In production, this should be disabled or protected
	if os.Getenv("ENABLE_SWAGGER") == "true" || gin.Mode() == gin.DebugMode {
		r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	}

	// 5️⃣ Setup all API routes
	api.SetupRoutes(r)

	// 6️⃣ Protected route example
	r.GET("/protected", middleware.AuthMiddleware(), func(c *gin.Context) {
		userID, _ := c.Get("userID")
		roleID, _ := c.Get("roleID")
		c.JSON(200, gin.H{
			"message": "You are authorized",
			"userID":  userID,
			"roleID":  roleID,
		})
	})

	// 7️⃣ Start server
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("Server starting on port %s...", port)
	if err := r.Run(":" + port); err != nil {
		log.Fatalf("Failed to run server: %v", err)
	}
}

